### ISSUE TITLE
Verify Cochise College is still offering tutoring to UA CAST students

### ISSUE THREAD

**Issue by mothsinthemachine** [UAAppComp/onboarding#2]
Can anyone verify if Cochise College in Sierra Vista and Douglas, AZ, is still offering tutoring to UA CAST students?

If not, then this will need to be updated on the ReadMe.

![Screenshot 2023-05-11 105010](https://github.com/UAAppComp/onboarding/assets/72046993/8f7f20cd-e3e9-46a6-b83a-77dd6a997a7a)

**Comment by ryanstraight** [comment]
Checking with Advising. Will update if needed.
